# Generated by Django 4.2.7 on 2026-03-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assertion_type', models.CharField(choices=[('invariant', 'Network Invariant'), ('safety', 'Safety Property'), ('liveness', 'Liveness Property'), ('isolation', 'Isolation Assertion'), ('authentication', 'Authentication Assertion')], max_length=30)),
                ('description', models.TextField()),
                ('assertion_logic', models.TextField(help_text='Formal assertion in predicate logic')),
                ('expected_result', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_properties', models.IntegerField(default=0)),
                ('verified_count', models.IntegerField(default=0)),
                ('violated_count', models.IntegerField(default=0)),
                ('assertions', models.ManyToManyField(blank=True, related_name='jobs', to='formal_verification.securityassertion')),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdncontroller')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('reachability', 'Reachability Property'), ('isolation', 'Network Isolation'), ('loop_freedom', 'Loop Freedom'), ('consistency', 'Flow Consistency'), ('access_control', 'Access Control Policy'), ('waypointing', 'Waypointing'), ('blackhole', 'Blackhole Detection')], max_length=30)),
                ('description', models.TextField()),
                ('formal_expression', models.TextField(help_text='Formal logic expression or assertion')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdncontroller')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdnswitch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('violated', 'Violated'), ('unknown', 'Unknown')], max_length=20)),
                ('property_name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('counterexample', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formal_verification.securityassertion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='formal_verification.verificationjob')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formal_verification.verificationrule')),
            ],
        ),
        migrations.AddField(
            model_name='verificationjob',
            name='rules',
            field=models.ManyToManyField(related_name='jobs', to='formal_verification.verificationrule'),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('auth', 'Authentication'), ('config_change', 'Configuration Change'), ('verification', 'Verification'), ('alert', 'Security Alert'), ('simulation', 'Simulation'), ('policy', 'Policy Change'), ('access', 'Access Control')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('component', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
