from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, Http404
from django.contrib import messages
from django.utils import timezone
from .models import Report
from vulnerability_analysis.models import Vulnerability
from attack_simulation.models import AttackScenario, SimulationResult
from network_model.models import SDNController, SDNSwitch, SDNHost, CommunicationFlow
import os


def generate_pdf_report(report, report_type):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.enums import TA_CENTER
    from django.conf import settings

    os.makedirs(os.path.join(settings.MEDIA_ROOT, 'reports'), exist_ok=True)
    filepath = os.path.join(settings.MEDIA_ROOT, 'reports', f'report_{report.id}.pdf')

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            rightMargin=40, leftMargin=40, topMargin=60, bottomMargin=40)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('T', parent=styles['Title'],
                                 textColor=colors.HexColor('#1e3a5f'), fontSize=22, spaceAfter=6)
    heading_style = ParagraphStyle('H', parent=styles['Heading2'],
                                   textColor=colors.HexColor('#2563eb'), fontSize=13, spaceAfter=4)
    sub_style = ParagraphStyle('S', parent=styles['Normal'],
                               textColor=colors.grey, fontSize=11, spaceAfter=16)
    body = styles['Normal']
    story = []

    # Header
    story.append(Paragraph('SDN Security Analysis System', title_style))
    story.append(Paragraph(report.title, sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#2563eb')))
    story.append(Spacer(1, 0.2 * inch))

    meta = [
        ['Report Type:', report.get_report_type_display()],
        ['Generated By:', str(report.generated_by)],
        ['Date:', timezone.now().strftime('%Y-%m-%d %H:%M UTC')],
    ]
    mt = Table(meta, colWidths=[1.8 * inch, 4 * inch])
    mt.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#1e3a5f')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(mt)
    story.append(Spacer(1, 0.3 * inch))

    # Executive Summary
    story.append(Paragraph('Executive Summary', heading_style))
    total_v = Vulnerability.objects.count()
    critical_v = Vulnerability.objects.filter(severity='critical').count()
    patched_v = Vulnerability.objects.filter(is_patched=True).count()
    total_s = AttackScenario.objects.filter(status='completed').count()
    successful_s = SimulationResult.objects.filter(is_successful=True).count()
    summary_text = (
        f"This report covers the security assessment of the SDN infrastructure. "
        f"A total of {total_v} vulnerabilities were identified, of which {critical_v} are critical severity "
        f"and {patched_v} have been patched. {total_s} attack simulations were executed, "
        f"with {successful_s} demonstrating successful exploitation paths."
    )
    story.append(Paragraph(summary_text, body))
    story.append(Spacer(1, 0.2 * inch))

    # Network Overview
    if report_type in ('network', 'full'):
        story.append(Paragraph('Network Infrastructure Overview', heading_style))
        controllers = SDNController.objects.all()
        net_data = [['Component', 'Name', 'IP Address', 'Status']]
        for c in controllers:
            net_data.append(['Controller', c.name, c.ip_address, c.status.upper()])
        for s in SDNSwitch.objects.all():
            net_data.append(['Switch', s.name, s.ip_address, s.status.upper()])
        for h in SDNHost.objects.all()[:10]:
            net_data.append(['Host', h.name, h.ip_address, 'MALICIOUS' if h.is_malicious else 'NORMAL'])
        if len(net_data) > 1:
            nt = Table(net_data, colWidths=[1.2 * inch, 1.8 * inch, 1.8 * inch, 1.2 * inch])
            nt.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f4ff')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(nt)
        story.append(Spacer(1, 0.25 * inch))

    # Vulnerabilities
    if report_type in ('vulnerability', 'full'):
        story.append(Paragraph('Vulnerability Analysis', heading_style))
        story.append(Paragraph(
            f'Total: {total_v} | Critical: {critical_v} | '
            f'Patched: {patched_v} | Unpatched: {total_v - patched_v}', body))
        story.append(Spacer(1, 0.1 * inch))
        vulns = Vulnerability.objects.all()[:20]
        vd = [['Vulnerability', 'Type', 'Severity', 'CVSS', 'Status']]
        for v in vulns:
            vd.append([v.name[:38], v.get_vuln_type_display(),
                       v.get_severity_display(), str(v.cvss_score),
                       'Patched' if v.is_patched else 'Open'])
        if len(vd) > 1:
            vt = Table(vd, colWidths=[2.2 * inch, 1.4 * inch, 0.9 * inch, 0.6 * inch, 0.8 * inch])
            vt.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dc2626')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fff5f5')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(vt)
        story.append(Spacer(1, 0.25 * inch))

    # Simulations
    if report_type in ('simulation', 'full'):
        story.append(Paragraph('Attack Simulation Results', heading_style))
        scenarios = AttackScenario.objects.filter(status='completed')
        sd = [['Scenario', 'Attack Type', 'Severity', 'Outcome', 'Impact']]
        for s in scenarios[:15]:
            res = getattr(s, 'result', None)
            sd.append([s.name[:30], s.get_attack_type_display(),
                       s.get_severity_display(),
                       'SUCCESS' if res and res.is_successful else 'BLOCKED',
                       str(s.impact_score)])
        if len(sd) > 1:
            st = Table(sd, colWidths=[1.8 * inch, 1.6 * inch, 0.9 * inch, 0.9 * inch, 0.7 * inch])
            st.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#d97706')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fffbf0')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(st)
        story.append(Spacer(1, 0.25 * inch))

    # Recommendations
    story.append(Paragraph('Security Recommendations', heading_style))
    recs = [
        ('Critical', 'Enable TLS mutual authentication for all controller-switch OpenFlow connections'),
        ('Critical', 'Implement dynamic ARP inspection to prevent ARP spoofing attacks'),
        ('High', 'Deploy rate limiting on control plane to prevent DoS/saturation attacks'),
        ('High', 'Enable controller clustering to eliminate single points of failure'),
        ('High', 'Implement cryptographic signing of flow rules to prevent tampering'),
        ('Medium', 'Deploy network anomaly detection at the SDN controller'),
        ('Medium', 'Regularly audit flow tables for unauthorized or conflicting rules'),
        ('Medium', 'Separate management plane from data plane networks'),
        ('Low', 'Implement comprehensive logging and SIEM integration'),
        ('Low', 'Conduct periodic formal verification runs to confirm security properties'),
    ]
    rec_data = [['Priority', 'Recommendation']]
    for priority, rec in recs:
        rec_data.append([priority, rec])
    rt = Table(rec_data, colWidths=[0.9 * inch, 5.1 * inch])
    rt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#16a34a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0fff4')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(rt)

    doc.build(story)
    return filepath


@login_required
def report_list(request):
    # Users see their own reports; admins see all
    if request.user.role == 'admin':
        reports = Report.objects.select_related('generated_by').all()
    else:
        reports = Report.objects.select_related('generated_by').filter(generated_by=request.user)
    return render(request, 'reports/report_list.html', {'reports': reports})


@login_required
def generate_report(request):
    if request.method == 'POST':
        report_type = request.POST.get('report_type', 'full')
        titles = {
            'vulnerability': 'Vulnerability Analysis Report',
            'simulation': 'Attack Simulation Report',
            'full': 'Full Security Assessment Report',
            'network': 'Network Topology Report',
        }
        report = Report.objects.create(
            title=titles.get(report_type, 'Security Report'),
            report_type=report_type,
            generated_by=request.user,
            status='generating',
        )
        try:
            generate_pdf_report(report, report_type)
            report.file_path = f'reports/report_{report.id}.pdf'
            report.status = 'ready'
            report.summary = (
                f'Generated by {request.user.get_full_name() or request.user.username}. '
                f'Covers {Vulnerability.objects.count()} vulnerabilities and '
                f'{AttackScenario.objects.filter(status="completed").count()} simulation results.'
            )
            report.save()
            messages.success(request, 'Report generated successfully! You can now download it.')
        except Exception as e:
            report.status = 'failed'
            report.save()
            messages.error(request, f'Report generation failed: {str(e)}')
        return redirect('reports:list')
    return render(request, 'reports/generate.html', {'report_types': Report.REPORT_TYPES})


@login_required
def download_report(request, pk):
    report = get_object_or_404(Report, pk=pk)
    # Users can only download their own reports
    if request.user.role != 'admin' and report.generated_by != request.user:
        messages.error(request, 'You can only download your own reports.')
        return redirect('reports:list')
    if report.file_path and os.path.exists(report.file_path.path):
        return FileResponse(
            open(report.file_path.path, 'rb'),
            content_type='application/pdf',
            as_attachment=True,
            filename=f'{report.title}.pdf'
        )
    raise Http404("Report file not found")


@login_required
def report_detail(request, pk):
    report = get_object_or_404(Report, pk=pk)
    if request.user.role != 'admin' and report.generated_by != request.user:
        messages.error(request, 'Access denied.')
        return redirect('reports:list')
    return render(request, 'reports/report_detail.html', {'report': report})
