# Generated by Django 4.2.7 on 2026-03-09 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('attack_type', models.CharField(choices=[('arp_spoofing', 'ARP Spoofing'), ('dos_flood', 'DoS Flood Attack'), ('topology_poisoning', 'Topology Poisoning'), ('packet_injection', 'Packet Injection'), ('controller_saturation', 'Controller Saturation'), ('flow_table_overflow', 'Flow Table Overflow'), ('man_in_middle', 'Man in the Middle')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('feasibility_score', models.FloatField(default=0.0)),
                ('impact_score', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('attacker_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdnhost')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdncontroller')),
                ('target_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_model.sdnswitch')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField(default=False)),
                ('packets_sent', models.IntegerField(default=0)),
                ('packets_dropped', models.IntegerField(default=0)),
                ('affected_flows', models.IntegerField(default=0)),
                ('compromised_nodes', models.JSONField(default=list)),
                ('attack_vector', models.TextField()),
                ('timeline', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('raw_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='attack_simulation.attackscenario')),
            ],
        ),
    ]
