# Generated by Django 4.2.7 on 2026-03-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDNController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=6633)),
                ('controller_type', models.CharField(default='OpenDaylight', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('compromised', 'Compromised')], default='active', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDNSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dpid', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('of_version', models.CharField(default='1.3', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('compromised', 'Compromised')], default='active', max_length=20)),
                ('flow_table_size', models.IntegerField(default=1000)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='network_model.sdncontroller')),
            ],
        ),
        migrations.CreateModel(
            name='SDNHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('port_number', models.IntegerField()),
                ('os_type', models.CharField(blank=True, max_length=50)),
                ('is_malicious', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='network_model.sdnswitch')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('OpenFlow', 'OpenFlow')], max_length=20)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('bandwidth', models.FloatField(default=0.0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('packet_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='network_model.sdnhost')),
                ('source_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='network_model.sdnhost')),
            ],
        ),
    ]
